  INFO root [2018-08-27 09:40:36,994] - 
  INFO root [2018-08-27 09:40:36,995] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-27 09:40:36,995] - Resmgr::initialize: KBE_ROOT=G:/kbengine-2.2.0/
  INFO root [2018-08-27 09:40:36,996] - Resmgr::initialize: KBE_RES_PATH=G:/kbengine-2.2.0/kbe/res/;G:/kbengine-2.2.0/Server/;G:/kbengine-2.2.0/Server/scripts/;G:/kbengine-2.2.0/Server/res/
  INFO root [2018-08-27 09:40:36,996] - Resmgr::initialize: KBE_BIN_PATH=G:/kbengine-2.2.0/kbe/bin/server/
  INFO root [2018-08-27 09:40:36,999] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:20013 )
  INFO root [2018-08-27 09:40:37,000] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.149:20013, SOMAXCONN=128.
  INFO root [2018-08-27 09:40:37,001] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:63307 )
  INFO root [2018-08-27 09:40:37,001] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.149:63307, SOMAXCONN=128.
  INFO root [2018-08-27 09:40:37,002] - server-configs:
  INFO root [2018-08-27 09:40:37,002] - 	internalTcpAddr : 192.168.0.149:63307
  INFO root [2018-08-27 09:40:37,002] - 	externalTcpAddr : 192.168.0.149:20013
  INFO root [2018-08-27 09:40:37,002] - 	componentID : 9000
  INFO root [2018-08-27 09:40:37,250] - Components::findLogger: found logger, addr:192.168.0.149:63283
  INFO root [2018-08-27 09:40:37,250] - Components::addComponent: reset orderLog, uid=21474!
  INFO root [2018-08-27 09:40:37,250] - Components::addComponent[logger], uid=21474, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-27 09:40:37,255] - ---- loginapp Version: 2.2.0. ScriptVersion: 0.1.0. Protocol: CE9C0D15469CA4C743FAB2554D129037. Config: Debug X86. Built: 18:11:40 Aug 17 2018. AppID: 9000. UID: 21474. PID: 9564 ----
  INFO root [2018-08-27 09:40:37,255] - Server : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 4194303kB RAM
  INFO root [2018-08-27 09:40:37,255] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-27 09:40:37,256] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-27 09:40:37,383] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-27 09:40:37,384] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-27 09:40:37,384] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-27 09:40:37,387] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-27 09:40:37,387] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-27 09:40:37,387] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-27 09:40:37,388] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-27 09:40:37,420] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-27 09:40:37,452] - Script::install(): is successfully, Python=(3.4.2 (default, Aug 17 2018, 18:11:36) [MSC v.1914 32 bit (Intel)])!
  INFO root [2018-08-27 09:40:37,452] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-27 09:40:37,467] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-27 09:40:37,467] - TelnetServer server is running on port 31000
  INFO root [2018-08-27 09:40:37,730] - ---- loginapp is running ----
 DEBUG root [2018-08-27 09:40:37,731] - Components::process(): Request for the process of identity...
  WARN root [2018-08-27 09:40:43,809] - Forwarding logs to logger[192.168.0.149:63283/0/0/0]...
 ERROR root [2018-08-27 10:06:15,594] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-08-27 10:06:15,627] - Components::findComponents: receive error!
 ERROR root [2018-08-27 10:07:41,362] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-08-27 10:07:41,365] - Components::findComponents: receive error!
 ERROR root [2018-08-27 10:08:04,148] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-08-27 10:08:04,152] - Components::findComponents: receive error!
 ERROR root [2018-08-27 10:08:04,156] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-27 10:08:04,157] - The following logs sent to logger failed:
  WARN root [2018-08-27 10:08:04,157] - ==> [2018-08-27 10:08:04 155] TCPPacketReceiver::processPendingEvents(192.168.0.149:63283): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-27 10:08:04,158] - ==> [2018-08-27 10:08:04 156] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-27 10:08:05,158] - Components::findComponents: find dbmgr(798)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2018-08-27 10:08:06,917] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2018-08-27 10:08:06,918] - Components::findComponents: receive error!
  INFO root [2018-08-27 10:48:51,779] - 
  INFO root [2018-08-27 10:48:51,780] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-27 10:48:51,781] - Resmgr::initialize: KBE_ROOT=G:/kbengine-2.2.0/
  INFO root [2018-08-27 10:48:51,782] - Resmgr::initialize: KBE_RES_PATH=G:/kbengine-2.2.0/kbe/res/;G:/kbengine-2.2.0/Server/;G:/kbengine-2.2.0/Server/scripts/;G:/kbengine-2.2.0/Server/res/
  INFO root [2018-08-27 10:48:51,782] - Resmgr::initialize: KBE_BIN_PATH=G:/kbengine-2.2.0/kbe/bin/server/
  INFO root [2018-08-27 10:48:51,791] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:20013 )
  INFO root [2018-08-27 10:48:51,791] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.149:20013, SOMAXCONN=128.
  INFO root [2018-08-27 10:48:51,795] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:60642 )
  INFO root [2018-08-27 10:48:51,795] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.149:60642, SOMAXCONN=128.
  INFO root [2018-08-27 10:48:51,795] - server-configs:
  INFO root [2018-08-27 10:48:51,796] - 	internalTcpAddr : 192.168.0.149:60642
  INFO root [2018-08-27 10:48:51,796] - 	externalTcpAddr : 192.168.0.149:20013
  INFO root [2018-08-27 10:48:51,796] - 	componentID : 9000
  INFO root [2018-08-27 10:48:52,425] - Components::findLogger: found logger, addr:192.168.0.149:60630
  INFO root [2018-08-27 10:48:52,426] - Components::addComponent: reset orderLog, uid=2183!
  INFO root [2018-08-27 10:48:52,426] - Components::addComponent[logger], uid=2183, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-27 10:48:52,439] - ---- loginapp Version: 2.2.0. ScriptVersion: 0.1.0. Protocol: CE9C0D15469CA4C743FAB2554D129037. Config: Debug X86. Built: 18:11:40 Aug 17 2018. AppID: 9000. UID: 2183. PID: 14972 ----
  INFO root [2018-08-27 10:48:52,440] - Server : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 4194303kB RAM
  INFO root [2018-08-27 10:48:52,441] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-27 10:48:52,442] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-27 10:48:52,610] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-27 10:48:52,611] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-27 10:48:52,612] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-27 10:48:52,621] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-27 10:48:52,621] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-27 10:48:52,622] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-27 10:48:52,624] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-27 10:48:52,720] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-27 10:48:52,811] - Script::install(): is successfully, Python=(3.4.2 (default, Aug 17 2018, 18:11:36) [MSC v.1914 32 bit (Intel)])!
  INFO root [2018-08-27 10:48:52,812] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-27 10:48:52,817] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-27 10:48:52,818] - TelnetServer server is running on port 31000
  INFO root [2018-08-27 10:48:53,777] - ---- loginapp is running ----
 DEBUG root [2018-08-27 10:48:53,779] - Components::process(): Request for the process of identity...
  WARN root [2018-08-27 10:49:00,015] - Forwarding logs to logger[192.168.0.149:60630/0/0/0]...
 ERROR root [2018-08-27 10:49:38,326] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-27 10:49:38,331] - The following logs sent to logger failed:
  WARN root [2018-08-27 10:49:38,332] - ==> [2018-08-27 10:49:38 321] TCPPacketReceiver::processPendingEvents(192.168.0.149:60630): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-27 10:49:38,332] - ==> [2018-08-27 10:49:38 327] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-27 10:49:49,024] - 
  INFO root [2018-08-27 10:49:49,024] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-27 10:49:49,026] - Resmgr::initialize: KBE_ROOT=G:/kbengine-2.2.0/
  INFO root [2018-08-27 10:49:49,026] - Resmgr::initialize: KBE_RES_PATH=G:/kbengine-2.2.0/kbe/res/;G:/kbengine-2.2.0/Server/;G:/kbengine-2.2.0/Server/scripts/;G:/kbengine-2.2.0/Server/res/
  INFO root [2018-08-27 10:49:49,026] - Resmgr::initialize: KBE_BIN_PATH=G:/kbengine-2.2.0/kbe/bin/server/
  INFO root [2018-08-27 10:49:49,033] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:20013 )
  INFO root [2018-08-27 10:49:49,033] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.0.149:20013, SOMAXCONN=128.
  INFO root [2018-08-27 10:49:49,037] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.0.149 ( 192.168.0.149:60835 )
  INFO root [2018-08-27 10:49:49,038] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.0.149:60835, SOMAXCONN=128.
  INFO root [2018-08-27 10:49:49,038] - server-configs:
  INFO root [2018-08-27 10:49:49,038] - 	internalTcpAddr : 192.168.0.149:60835
  INFO root [2018-08-27 10:49:49,038] - 	externalTcpAddr : 192.168.0.149:20013
  INFO root [2018-08-27 10:49:49,039] - 	componentID : 9000
  INFO root [2018-08-27 10:49:50,024] - Components::findLogger: found logger, addr:192.168.0.149:60830
  INFO root [2018-08-27 10:49:50,026] - Components::addComponent: reset orderLog, uid=2372!
  INFO root [2018-08-27 10:49:50,026] - Components::addComponent[logger], uid=2372, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-27 10:49:50,037] - ---- loginapp Version: 2.2.0. ScriptVersion: 0.1.0. Protocol: CE9C0D15469CA4C743FAB2554D129037. Config: Debug X86. Built: 18:11:40 Aug 17 2018. AppID: 9000. UID: 2372. PID: 15892 ----
  INFO root [2018-08-27 10:49:50,038] - Server : Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz with 4194303kB RAM
  INFO root [2018-08-27 10:49:50,039] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-27 10:49:50,039] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-27 10:49:50,209] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-27 10:49:50,210] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-27 10:49:50,211] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-27 10:49:50,219] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-27 10:49:50,220] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-27 10:49:50,220] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-27 10:49:50,221] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-27 10:49:50,309] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-27 10:49:50,406] - Script::install(): is successfully, Python=(3.4.2 (default, Aug 17 2018, 18:11:36) [MSC v.1914 32 bit (Intel)])!
  INFO root [2018-08-27 10:49:50,407] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-27 10:49:50,412] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-27 10:49:50,412] - TelnetServer server is running on port 31000
  INFO root [2018-08-27 10:49:51,487] - ---- loginapp is running ----
 DEBUG root [2018-08-27 10:49:51,489] - Components::process(): Request for the process of identity...
  WARN root [2018-08-27 10:49:57,699] - Forwarding logs to logger[192.168.0.149:60830/0/0/0]...
